services:

  # Apache httpd webserver 
  httpd:
    container_name: httpd-server
    image: httpd:2.4.62
    # TODO: Use a env var for the host port, this will be usefull when deploying
    ports:
      - 80:80
    working_dir: /var/www
    # TODO: Create DockerFile to copy configs instead of using volume 
    volumes:
      - ./services/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./services/httpd/extra:/usr/local/apache2/conf/extra
    volumes_from:
      - data

  # PHP web app
  php:
    container_name: php-fpm
    build:
      dockerfile: ./services/php/DockerFile
    links:
      - httpd:localhost.local
    volumes_from:
      - data
    depends_on:
      - httpd 

  data:
    container_name: source_code
    image: busybox:stable
    # TODO: Create DockerFile to copy the source to /var/www
    # New entry in volume will look like '/var/www' instead of './app:/var/www'
    volumes:
      - ./app:/var/www

  db:
    container_name: mysql
    image: mysql:8.4 
    volumes:
      - mysqldata:/var/lib/mysql
    # TODO: Remove port after developement
    ports:
      - 33060:3306 
    # TODO: replace with environment variable values from .env
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: temp-db

volumes:
  mysqldata:
