services:

  # Apache httpd webserver 
  httpd:
    container_name: httpd-server
    image: httpd:2.4.62
    ports:
      - ${SERVER_PORT}:443
    working_dir: /var/www
    # TODO:: Rotate server crt before submission
    volumes:
      - ./services/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./services/httpd/extra:/usr/local/apache2/conf/extra
      - ./services/httpd/keys/server.crt:/usr/local/apache2/keys/server.crt
      - ./services/httpd/keys/server.key:/usr/local/apache2/keys/server.key
    volumes_from:
      - data
    networks: 
      - web-app-network

  # PHP web app
  php:
    #TODO: Copy php-production.ini file to docker container
    # Make sure "display_errors = Off" in php-production.ini file. Reference: https://stackoverflow.com/questions/8928021/stop-printing-php-error-messages-to-browser, https://forums.docker.com/t/docker-compose-yml-services-for-php-fpm/52677
    container_name: php-fpm
    env_file: .env
    build:
      context: ./services/php
      dockerfile: ./DockerFile
    volumes_from:
      - data
    depends_on:
      - httpd 
    networks: 
      - web-app-network

  data:
    container_name: source_code
    image: busybox:stable
    volumes:
      - ./app:/var/www

  db:
    container_name: ${MYSQL_HOSTNAME}
    image: mysql:8.4
    volumes:
      - ./services/sql/app-data-dump.sql:/docker-entrypoint-initdb.d/app-data-dump.sql
    # TODO: Remove port after developement
    ports:
      - 33060:3306 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks: 
      - web-app-network

networks:
  web-app-network:
