services:

  # Apache httpd webserver 
  httpd:
    container_name: httpd-server
    ports:
      - ${SERVER_PORT}:443
    build: 
      context: .
      dockerfile: ./services/httpd/DockerFile
    depends_on:
      - data 
    volumes_from:
      - data
    networks: 
      - web-app-network

  # PHP web app
  php:
    container_name: php-fpm
    env_file: .env
    build:
      context: .
      dockerfile: ./services/php/DockerFile
    depends_on:
      - data 
    volumes_from:
      - data
    networks: 
      - web-app-network

  data:
    container_name: source-code
    build:
      context: .
      dockerfile: ./services/data/DockerFile
    volumes:
      - /var/www/
    # TODO: remove watch before production
    develop:
      watch:
        - path: ./app 
          action: sync 
          target: /var/www/html

  db:
    container_name: ${MYSQL_HOSTNAME}
    image: mysql:8.4
    volumes:
      - ./services/sql/app-data-dump.sql:/docker-entrypoint-initdb.d/app-data-dump.sql
    # TODO: Remove port after developement
    ports:
      - 33060:3306 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks: 
      - web-app-network

networks:
  web-app-network:
