# Get php-fpm base image
FROM php:8.1.31-fpm-alpine3.21 

# Install php Extensions
RUN docker-php-ext-install mysqli

# TODO: Copy the php-production.ini before submission
COPY php.ini-development /usr/local/etc/php/php.ini

# Set the working dir for php-fpm
WORKDIR /var/www
